export const HANDLE_ON_POST_READY_NOTIFICATION_SUCCESS = "HANDLE_ON_POST_READY_NOTIFICATION_SUCCESS";
export const HANDLE_ON_POST_READY_NOTIFICATION_FAILURE = "HANDLE_ON_POST_READY_NOTIFICATION_FAILURE";

export const QUERY_NUM_OF_UNREAD_NOTIFICATIONS = "QUERY_NUM_OF_UNREAD_NOTIFICATIONS";
export const QUERY_NUM_OF_UNREAD_NOTIFICATIONS_SUCCESS = "QUERY_NUM_OF_UNREAD_NOTIFICATIONS_SUCCESS";
export const QUERY_NUM_OF_UNREAD_NOTIFICATIONS_FAILURE = "QUERY_NUM_OF_UNREAD_NOTIFICATIONS_FAILURE";

export const READ_NOTIFICATIONS_REQUEST = "READ_NOTIFICATIONS_REQUEST";
export const READ_NOTIFICATIONS_SUCCESS = "READ_NOTIFICATIONS_SUCCESS";
export const READ_NOTIFICATIONS_FAILURE = "READ_NOTIFICATIONS_FAILURE";