export const READ_USER_PROFILE_REQUEST = "READ_USER_PROFILE_REQUEST";
export const READ_USER_PROFILE_SUCCESS = "READ_USER_PROFILE_SUCCESS";
export const READ_USER_PROFILE_FAILURE = "READ_USER_PROFILE_FAILURE";

export const FOLLOW_USER_REQUEST = "FOLLOW_USER_REQUEST";
export const FOLLOW_USER_SUCCESS = "FOLLOW_USER_SUCCESS";
export const FOLLOW_USER_FAILURE = "FOLLOW_USER_FAILURE";