export const READ_USER_PROFILE_REQUEST = "READ_USER_PROFILE_REQUEST";
export const READ_USER_PROFILE_SUCCESS = "READ_USER_PROFILE_SUCCESS";
export const READ_USER_PROFILE_FAILURE = "READ_USER_PROFILE_FAILURE";