export const READ_RECOMMENDED_USERS_REQUEST = "READ_RECOMMENDED_USERS_REQUEST";
export const READ_RECOMMENDED_USERS_SUCCESS = "READ_RECOMMENDED_USERS_SUCCESS";
export const READ_RECOMMENDED_USERS_FAILURE = "READ_RECOMMENDED_USERS_FAILURE";