name: Remote Staging Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - staging

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}    

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1        

      - name: Create Environment
        run: |
          echo "Creating environment file..."
          echo "REACT_APP_BACKEND_URL=${{ secrets.REACT_APP_BACKEND_URL }}" >> staging.env
          echo "REACT_APP_BACKEND_SOCKET_URL=${{ secrets.REACT_APP_BACKEND_SOCKET_URL }}" >> staging.env
          echo "REACT_APP_NAME=${{ secrets.REACT_APP_NAME }}" >> staging.env              

      - name: Build Docker Image
        run: docker build -f dockerfiles/react.dockerfile -t odox700/org-ydotcom-fe:staging-2.0 .              

      - name: Push image to docker hub
        run: docker push odox700/org-ydotcom-fe:staging-2.0

  deploy:
    needs: build
    runs-on: MyRandomOrganization-Runner

    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }} 

      - name: Pull image from docker hub
        run: docker pull odox700/org-ydotcom-fe:staging-2.0

      - name: Delete old container
        run: docker rm -f ydotcom

      - name: Run Docker Container
        run: |
          docker run -d \
          -p 280:80 \
          --name ydotcom \
          odox700/org-ydotcom-fe:staging-2.0
